spring:
  batch:
    job:
      enabled: false
---
spring:
  profiles: mariadb
  datasource:
    hikari:
      jdbc-url: jdbc:mariadb://codedot.co.kr:3306/test_user_01?characterEncoding=UTF-8
      username: test_user_01
      password: dl945pa
      driver-class-name: org.mariadb.jdbc.Driver